apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data:
  odoo.conf: |
     [options]
     ; This is the password that allows database operations:
     admin_passwd = @Fsone2020#IT

     addons_path = /mnt/extra-addons
     data_dir = /var/lib/odoo

     db_host = postgres
     db_user = odoo_user2
     db_password = DBP@ssw0rd!
     db_port = 5432
     #list_db = True
     ;odoo_report_url = http://0.0.0.0:8069
     # proxy_mode = True

     limit_time_real = 5000
